<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MasterProject;
use Carbon\Carbon;

class MasterProjectsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $now=Carbon::now();
      $MasterProject=new MasterProject;
      $MasterProject::insert([
        ['clientId'=>'1','contractTypeId'=>'4','projectName'=>'無稼働時間','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'2','contractTypeId'=>'4','projectName'=>'朝礼・夕礼','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'2','contractTypeId'=>'4','projectName'=>'庶務（電話取次・清掃・報告書作成・諸雑務）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'2','contractTypeId'=>'4','projectName'=>'社内会議','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'2','contractTypeId'=>'4','projectName'=>'自己学習','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'2','contractTypeId'=>'4','projectName'=>'フィロソフィー教育','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'2','contractTypeId'=>'4','projectName'=>'その他（社内業務）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'2','contractTypeId'=>'4','projectName'=>'社内インフラ（社内業務）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'5','contractTypeId'=>'4','projectName'=>'監視・日次業務','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'5','contractTypeId'=>'4','projectName'=>'新規PJ・受注事前技術調査・検証','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'5','contractTypeId'=>'4','projectName'=>'脆弱性調査（全案件共通）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'5','contractTypeId'=>'4','projectName'=>'運用インフラ（機器対応・セキュリティ対応）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'5','contractTypeId'=>'4','projectName'=>'運用庶務（運用チームでの資料作成・会議）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'5','contractTypeId'=>'4','projectName'=>'終了案件対応・瑕疵対応','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'5','contractTypeId'=>'4','projectName'=>'OJT','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'6','contractTypeId'=>'4','projectName'=>'社内インフラ（社内請求業務）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'6','contractTypeId'=>'4','projectName'=>'ISMS・セキュリティ','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'6','contractTypeId'=>'4','projectName'=>'その他（社内請求業務）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'7','contractTypeId'=>'4','projectName'=>'見積作成（東京案件）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'7','contractTypeId'=>'4','projectName'=>'見積作成（松山案件）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'7','contractTypeId'=>'4','projectName'=>'営業支援（東京案件）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'7','contractTypeId'=>'4','projectName'=>'営業支援（松山案件）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'8','contractTypeId'=>'4','projectName'=>'開発支援','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'10','contractTypeId'=>'1','projectName'=>'ITコア様向け顧客サポート業務','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'11','contractTypeId'=>'1','projectName'=>'問合せリモートサポートサービス','workingTeamId'=>'4','slack_channel_name'=>'アドバンテック','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'11','contractTypeId'=>'1','projectName'=>'ドメインコントローラーサーバ等、保守サポート','workingTeamId'=>'4','slack_channel_name'=>'アドバンテック','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'11','contractTypeId'=>'1','projectName'=>'CAINS運用保守サポート','workingTeamId'=>'4','slack_channel_name'=>'アドバンテック','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'11','contractTypeId'=>'1','projectName'=>'端末初期設定・廃棄・HP追加修正・その他','workingTeamId'=>'4','slack_channel_name'=>'キッティング','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'11','contractTypeId'=>'1','projectName'=>'端末初期設定・廃棄・HP追加修正・その他','workingTeamId'=>'3','slack_channel_name'=>'web関連クールe含む','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'11','contractTypeId'=>'1','projectName'=>'勘定奉行・固定資産奉行・申告奉行・人事奉行システム月額運用費','workingTeamId'=>'4','slack_channel_name'=>'アドバンテック','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'11','contractTypeId'=>'1','projectName'=>'ドメインコントローラー運用（Azure）','workingTeamId'=>'4','slack_channel_name'=>'アドバンテック','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'11','contractTypeId'=>'3','projectName'=>'ウイルスバスターライセンス更新','workingTeamId'=>'4','slack_channel_name'=>'アドバンテック','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'11','contractTypeId'=>'1','projectName'=>'Azureサーバ維持費用','workingTeamId'=>'4','slack_channel_name'=>'アドバンテック','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'12','contractTypeId'=>'1','projectName'=>'WEBサイト保守及び遠隔バックアップシステム運用費用','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'12','contractTypeId'=>'1','projectName'=>'WEBサイト保守及び遠隔バックアップシステム運用費用','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'13','contractTypeId'=>'1','projectName'=>'生命保険経営学会　サーバ運用','workingTeamId'=>'4','slack_channel_name'=>'生保経営学会','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'13','contractTypeId'=>'1','projectName'=>'生命保険経営学会　サーバ運用','workingTeamId'=>'3','slack_channel_name'=>'生保経営学会','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'14','contractTypeId'=>'1','projectName'=>'パイオラックス様：サーバ運用保守・サポート','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'14','contractTypeId'=>'1','projectName'=>'パイオラックス様：サーバ運用保守・サポート','workingTeamId'=>'3','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'14','contractTypeId'=>'1','projectName'=>'近鉄エクスプレス様：緊急時ホームページ更新作業/サポート','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'15','contractTypeId'=>'3','projectName'=>'Microsoft 365 Business Basic導入サポート','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'16','contractTypeId'=>'3','projectName'=>'「すご味」・「すごモノ」サーバースポット対応（B案-2）','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'17','contractTypeId'=>'1','projectName'=>'三浦工業様ホームページの運用作業','workingTeamId'=>'4','slack_channel_name'=>'三浦工業web','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'18','contractTypeId'=>'1','projectName'=>'済生会今治病院様向けネットワーク監視報告書作成','workingTeamId'=>'4','slack_channel_name'=>'済生会今治病院','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'19','contractTypeId'=>'1','projectName'=>'ソフトウェア開発業務（井上隆、重藤、塩出、小池、在間）','workingTeamId'=>'3','slack_channel_name'=>'ツール開発','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'20','contractTypeId'=>'1','projectName'=>'WEBサイト用VPS運用費用','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'20','contractTypeId'=>'1','projectName'=>'WEBサイト用VPS運用費用','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'21','contractTypeId'=>'2','projectName'=>'2020年度JST Webサイト運用管理業務','workingTeamId'=>'4','slack_channel_name'=>'広報web','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'22','contractTypeId'=>'1','projectName'=>'Azureサーバ維持費用','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'23','contractTypeId'=>'1','projectName'=>'まるごと高知WEBサーバー保守サポート業務','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'23','contractTypeId'=>'1','projectName'=>'まるごと高知WEBサーバー保守サポート業務','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'24','contractTypeId'=>'2','projectName'=>'臨床研究情報検索ポータルサイト運用保守業務','workingTeamId'=>'4','slack_channel_name'=>'jrct','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'24','contractTypeId'=>'2','projectName'=>'臨床研究情報検索ポータルサイト運用保守業務','workingTeamId'=>'3','slack_channel_name'=>'jrct','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'24','contractTypeId'=>'2','projectName'=>'倫理審査委員会報告システムの運用保守','workingTeamId'=>'4','slack_channel_name'=>'倫理審査','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'24','contractTypeId'=>'2','projectName'=>'倫理審査委員会報告システムの運用保守','workingTeamId'=>'3','slack_channel_name'=>'倫理審査','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'24','contractTypeId'=>'2','projectName'=>'臨床研究データベースシステム令和2年度運用保守業務','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'24','contractTypeId'=>'2','projectName'=>'臨床研究データベースシステム令和2年度運用保守業務','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'24','contractTypeId'=>'2','projectName'=>'臨床研究ポータルサイトに係る機能改修業務（ICMJE論文投稿条件への対応等）','workingTeamId'=>'3','slack_channel_name'=>'rctポータル','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'25','contractTypeId'=>'3','projectName'=>'オキツモ様サイト消えま線改訂作業（9/17ご依頼分）','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'26','contractTypeId'=>'1','projectName'=>'遠隔地バックアップ','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'27','contractTypeId'=>'1','projectName'=>'ライブ監視業務（定例原子力ライブ配信）','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'27','contractTypeId'=>'1','projectName'=>'監視サービス費用','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'27','contractTypeId'=>'1','projectName'=>'24時間電話窓口対応（フリーダイヤル）','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'27','contractTypeId'=>'1','projectName'=>'ライブ監視業務（24時間チャット対応）','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'27','contractTypeId'=>'1','projectName'=>'新規監視運用費用（案件①）','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'27','contractTypeId'=>'1','projectName'=>'新規監視運用費用（案件②）','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'28','contractTypeId'=>'1','projectName'=>'高画質ビデオ素材ライブラリーサイトサーバ運用','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'28','contractTypeId'=>'1','projectName'=>'高画質ビデオ素材ライブラリーサイトサーバ運用','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'28','contractTypeId'=>'1','projectName'=>'UPS賃貸費用（月額）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'29','contractTypeId'=>'1','projectName'=>'自動応答システム稼動確認及び障害連絡業務','workingTeamId'=>'4','slack_channel_name'=>'電話正常性確認','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'30','contractTypeId'=>'1','projectName'=>'OA機器ヘルプデスク業務','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'30','contractTypeId'=>'1','projectName'=>'インターネットメディア運用支援業務','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'30','contractTypeId'=>'1','projectName'=>'WEBディレクション業務','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'31','contractTypeId'=>'1','projectName'=>'サイト企画制作等に関する業務委託に係る費用','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'32','contractTypeId'=>'1','projectName'=>'双生児DBシステム運用保守業務','workingTeamId'=>'4','slack_channel_name'=>'双生児db','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'32','contractTypeId'=>'1','projectName'=>'双生児DBシステム運用保守業務','workingTeamId'=>'3','slack_channel_name'=>'双生児db','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'32','contractTypeId'=>'1','projectName'=>'KAGRA WEBサーバ監視・運用','workingTeamId'=>'4','slack_channel_name'=>'kagra運用保守','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'32','contractTypeId'=>'1','projectName'=>'新領域創成科学研究科WEBサーバ監視運用業務（月額）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'32','contractTypeId'=>'1','projectName'=>'安否確認システム運用支援','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'32','contractTypeId'=>'1','projectName'=>'安否確認システムへのデータ投入作業','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'32','contractTypeId'=>'3','projectName'=>'試験支援システムの開発','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'33','contractTypeId'=>'3','projectName'=>'松山拠点放送局局車予約システムのサーバー及びデータ確認業務','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'33','contractTypeId'=>'1','projectName'=>'日本放送協会様運用業務追加サポート（一般職異動_転入）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'34','contractTypeId'=>'1','projectName'=>'「Ilbo」サーバ監視業務','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'34','contractTypeId'=>'1','projectName'=>'LOOOP様メール確認','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'35','contractTypeId'=>'1','projectName'=>'ＷＥＢメンテナンス＆サーバ運用','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'35','contractTypeId'=>'1','projectName'=>'ＷＥＢメンテナンス＆サーバ運用','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'36','contractTypeId'=>'4','projectName'=>'愛媛県行革分権課ITコンシェルジュ案件紹介料','workingTeamId'=>'2','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'37','contractTypeId'=>'1','projectName'=>'WEBシステム運用支援','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'38','contractTypeId'=>'1','projectName'=>'マイナビティーンズラボWEBサイトWordPress保守費用','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'39','contractTypeId'=>'1','projectName'=>'三浦工業様社内システム運用業務','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'40','contractTypeId'=>'3','projectName'=>'クリックジョブサイト修正費用','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'40','contractTypeId'=>'1','projectName'=>'クリックジョブサイト修正費用','workingTeamId'=>'3','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'40','contractTypeId'=>'1','projectName'=>'システム保守・監視費用','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'40','contractTypeId'=>'1','projectName'=>'システム保守・監視費用','workingTeamId'=>'3','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'41','contractTypeId'=>'1','projectName'=>'高津DCシステム監視','workingTeamId'=>'4','slack_channel_name'=>'sadr','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'41','contractTypeId'=>'1','projectName'=>'大林組ファイルサーバーDR運用','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'17','contractTypeId'=>'1','projectName'=>'日本放送協会常駐運用委託業務','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'42','contractTypeId'=>'1','projectName'=>'サーバ監視・オペレーション業務及び電話夜間受付業務','workingTeamId'=>'4','slack_channel_name'=>'監視オペレーション','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'43','contractTypeId'=>'1','projectName'=>'ホームページ追加修正業務委託','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'44','contractTypeId'=>'1','projectName'=>'ホームページ運用・保守','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'45','contractTypeId'=>'1','projectName'=>'しゃべるくんサポートセンター','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'46','contractTypeId'=>'1','projectName'=>'基幹ネットワークシステム運用管理・支援及び利用支援業務委託','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'47','contractTypeId'=>'4','projectName'=>'入札情報サービス','workingTeamId'=>'2','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'48','contractTypeId'=>'1','projectName'=>'高知まるごとネット運用保守業務','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'48','contractTypeId'=>'1','projectName'=>'高知まるごとネット運用保守業務','workingTeamId'=>'3','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'49','contractTypeId'=>'1','projectName'=>'高知家プロモーション実施におけるウェブサーバ運用保守委託業務','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'50','contractTypeId'=>'1','projectName'=>'道路情報提供機器保守委託業務（道情委第1号）','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'16','contractTypeId'=>'1','projectName'=>'すご味・すごモノデータベースサーバ保守','workingTeamId'=>'4','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'51','contractTypeId'=>'2','projectName'=>'サポートステーションネット運用保守・管理棟業務','workingTeamId'=>'4','slack_channel_name'=>'サポステ','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'51','contractTypeId'=>'2','projectName'=>'サポートステーションネット運用保守・管理棟業務','workingTeamId'=>'3','slack_channel_name'=>'サポステ','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'52','contractTypeId'=>'2','projectName'=>'H30年度日本映画情報システム運用管理業務','workingTeamId'=>'4','slack_channel_name'=>'日本映画情報システム','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'52','contractTypeId'=>'2','projectName'=>'H30年度日本映画情報システム運用管理業務','workingTeamId'=>'3','slack_channel_name'=>'日本映画情報システム','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'53','contractTypeId'=>'1','projectName'=>'機構ホームページ用サーバ運用管理委託','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'53','contractTypeId'=>'1','projectName'=>'機構ホームページ用サーバ運用管理委託','workingTeamId'=>'3','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'54','contractTypeId'=>'2','projectName'=>'ファイアーウォール装置運転監視業務','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'54','contractTypeId'=>'2','projectName'=>'ファイアーウォール装置運転監視業務','workingTeamId'=>'3','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'55','contractTypeId'=>'2','projectName'=>'栄養摂取状況調査結果入力・収集プログラムの機能強化及び運用業務','workingTeamId'=>'4','slack_channel_name'=>'総合','created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'56','contractTypeId'=>'2','projectName'=>'国産野菜の生産者と実需者を結ぶマッチングサイト構築及び保守運営支援業務（2021年2月まで開発按分）','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['clientId'=>'24','contractTypeId'=>'2','projectName'=>'臨床研究（試験）情報検索ポータルサイトのクラウド化のための改修業務(9/17〜3/31)','workingTeamId'=>'3','slack_channel_name'=>null,'created_at'=>$now,'updated_at'=>$now,],
      ]);
    }
}
