<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MasterShift;
use Carbon\Carbon;

class MasterShiftsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $now=Carbon::now();
      $MasterShift=new MasterShift;
      $MasterShift::insert([
        ['shiftName'=>'S','startHour'=>'9','startMinute'=>'0','endHour'=>'18','endMinute'=>'0','rest1StartHour'=>'12','rest1StartMinute'=>'0','rest1EndHour'=>'13','rest1EndMinute'=>'0','rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>'変形労働','workLocation'=>'本社','description'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'C','startHour'=>'8','startMinute'=>'0','endHour'=>'20','endMinute'=>'0','rest1StartHour'=>'12','rest1StartMinute'=>'0','rest1EndHour'=>'13','rest1EndMinute'=>'0','rest2StartHour'=>'18','rest2StartMinute'=>'0','rest2EndHour'=>'18','rest2EndMinute'=>'30','rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>'変形労働','workLocation'=>'本社','description'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'E','startHour'=>'20','startMinute'=>'0','endHour'=>'32','endMinute'=>'0','rest1StartHour'=>'24','rest1StartMinute'=>'0','rest1EndHour'=>'25','rest1EndMinute'=>'0','rest2StartHour'=>'30','rest2StartMinute'=>'0','rest2EndHour'=>'30','rest2EndMinute'=>'30','rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>'変形労働','workLocation'=>'本社','description'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'県庁','startHour'=>'8','startMinute'=>'30','endHour'=>'17','endMinute'=>'15','rest1StartHour'=>'12','rest1StartMinute'=>'0','rest1EndHour'=>'13','rest1EndMinute'=>'0','rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>'変形労働','workLocation'=>'県庁','description'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'NHK','startHour'=>'9','startMinute'=>'30','endHour'=>'18','endMinute'=>'0','rest1StartHour'=>'12','rest1StartMinute'=>'0','rest1EndHour'=>'13','rest1EndMinute'=>'0','rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>'変形労働','workLocation'=>'NHK','description'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'三浦','startHour'=>'8','startMinute'=>'30','endHour'=>'17','endMinute'=>'30','rest1StartHour'=>'10','rest1StartMinute'=>'0','rest1EndHour'=>'10','rest1EndMinute'=>'10','rest2StartHour'=>'12','rest2StartMinute'=>'40','rest2EndHour'=>'13','rest2EndMinute'=>'40','rest3StartHour'=>'15','rest3StartMinute'=>'0','rest3EndHour'=>'15','rest3EndMinute'=>'10','workStyle'=>'変形労働','workLocation'=>'三浦工業','description'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'H','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'休日：会社が定めた休日。シフトスタッフ以外は、土・日・祝日。シフトスタッフの場合はシフト表による。','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'休出','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'休日出勤：公休日に勤務した日。ただし、振替休日を決めて休日に勤務した場合は区分「振勤」を選択し、備考欄に振替えた休みの日を記入する事。　※「残業・休日申請書」を提出','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'有給','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'1日有給休暇日：勤務日に有給休暇を取得した日。但し、半日単位で取得した場合は「半給1」or「半給2」を選択　※「有給休暇申請書」の提出必須','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'半給','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'半日単位の有給休暇を取得した日　※「有給休暇申請書」の提出必須','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'欠勤','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'勤務日に欠勤した日。欠勤控除となる。（有給を使う場合や振休・代休・夏休・冬休の場合は区分が違います）　※「不就業届」提出必須','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'振勤','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'振替勤務：あらかじめ休日の振替日を指定して（振替日は同一週内（金〜木曜）且つ給与計算期間内である事）、本来休日と定められている日に勤務した日。備考欄に振替休日日を記入。　休日を振替えただけなので所定労働時間分の勤務が必要(複数日の休出時間足し合わせは不可)。　※「残業・休日申請書」を提出、『振替予定』欄に振替休日日(代休の場合は空欄）を記入。','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'振休','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'振替休日：本来休日と定められている日に労働する替わりに労働日と定められている日に休日を取得した日。備考欄に振替出勤日を記入。代休との違いとして、あらかじめ休日の振替日を指定しておく必要があり、なおかつ振替日は同一週内（金〜木曜）・給与計算期間内である事。※「残業・休日申請書」の『振替予定』に記入しておく事。','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'代休','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'休日出勤（所定労働時間以上の勤務時間数必要,複数日の休出時間足し合わせは不可）をし、その代わりに後日休日を取得した日。備考欄に対応する休日出勤日を記入。代休取得の場合は「代休届」を休出後速やかに提出する事。また代休日は無給である。','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'勤(宅)','startHour'=>'9','startMinute'=>'0','endHour'=>'18','endMinute'=>'0','rest1StartHour'=>'12','rest1StartMinute'=>'0','rest1EndHour'=>'13','rest1EndMinute'=>'0','rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>'変形労働','workLocation'=>'在宅','description'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'勤(半宅)','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>'変形労働','workLocation'=>'在宅','description'=>null,'created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'振勤(宅)','startHour'=>'9','startMinute'=>'0','endHour'=>'18','endMinute'=>'0','rest1StartHour'=>'12','rest1StartMinute'=>'0','rest1EndHour'=>'13','rest1EndMinute'=>'0','rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>'変形労働','workLocation'=>'在宅','description'=>'振替勤務：あらかじめ休日の振替日を指定して（振替日は同一週内（金〜木曜）且つ給与計算期間内である事）、本来休日と定められている日に勤務した日。備考欄に振替休日日を記入。　休日を振替えただけなので所定労働時間分の勤務が必要(複数日の休出時間足し合わせは不可)。　※「残業・休日申請書」を提出、『振替予定』欄に振替休日日(代休の場合は空欄）を記入。','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'休出(宅)','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>'変形労働','workLocation'=>'在宅','description'=>'休日出勤：公休日に勤務した日。ただし、振替休日を決めて休日に勤務した場合は区分「振勤」を選択し、備考欄に振替えた休みの日を記入する事。　※「残業・休日申請書」を提出','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'半給(宅)','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>'変形労働','workLocation'=>'在宅','description'=>'半日単位の有給休暇を取得した日　※「有給休暇申請書」の提出必須','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'夏休','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'休日：夏期休暇（2日間）','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'冬休','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'休日：冬期休暇（2日間）','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'特休','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'休日：その他会社が特に休日と定めた日。','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'産休','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'産前産後休暇：jimuまで届出必須','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'育休','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'育児休業：jimuまで届出必須','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'介休','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'介護休業：jimuまで届出必須','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'療休','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'業務上の負傷・疾病等により療養のため休業した日：jimuまで届出必須　※業務上によるもののみです。','created_at'=>$now,'updated_at'=>$now,],
        ['shiftName'=>'―','startHour'=>null,'startMinute'=>null,'endHour'=>null,'endMinute'=>null,'rest1StartHour'=>null,'rest1StartMinute'=>null,'rest1EndHour'=>null,'rest1EndMinute'=>null,'rest2StartHour'=>null,'rest2StartMinute'=>null,'rest2EndHour'=>null,'rest2EndMinute'=>null,'rest3StartHour'=>null,'rest3StartMinute'=>null,'rest3EndHour'=>null,'rest3EndMinute'=>null,'workStyle'=>null,'workLocation'=>null,'description'=>'給与計算期間途中の入社以前・退職以降の日。給与締日変更により勤務表既提出日が重複した日(例：5/1日付で末締→20日締に変更になった場合、5月度勤務表4/21-30は「ー」を選択)。','created_at'=>$now,'updated_at'=>$now,]
      ]);
    }
}
